name: WorkflowRelease
on:
    workflow_dispatch:
        inputs:
            version:
                description: "release version"
                required: true
                default: "unkown"
jobs:
    WorkflowRelease:
        name: WorkflowRelease
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup timezone
              uses: zcong1993/setup-timezone@master
              with:
                  timezone: Asia/Shanghai
            - name: Install MXE
              run: sudo bash install_mxe.sh
              working-directory: ./win64
            - name: Build
              run: sudo bash build.sh ${{ github.event.inputs.version }}
              working-directory: ./win64
            - name: Upload
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: ./win64/cdda-lizkes-${{ github.event.inputs.version }}-pure.7z
                  asset_name: cdda-windows-${{ github.event.inputs.version }}-pure-x64.7z
                  tag: ${{ github.event.inputs.version }}
                  overwrite: true
                  prerelease: true
